name: ace
description: For the Community

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  get: ^4.6.1
  hive: ^2.0.6
  shared_preferences: ^2.0.13
  sign_button: ^2.0.2
  lottie: ^1.2.2
  animated_splash_screen: ^1.2.0
  concentric_transition: ^1.0.1+1
  firebase: ^9.0.2
  google_sign_in: ^5.2.4
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  getwidget: ^2.0.5
  mask_text_input_formatter: ^2.1.0
  intl_phone_field: ^3.1.0
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  line_icons: ^2.0.1
  http: ^0.13.4
  sign_in_with_apple: ^3.3.0
  pinput: ^2.2.5
  smooth_page_indicator: ^1.0.0+2
  chewie: ^1.3.1
  video_player: ^2.3.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  razorpay_flutter: ^1.2.9
  slimy_card: ^1.0.4
  auto_size_text: ^3.0.0
  get_storage: ^2.0.3
  flutter_secure_storage: ^5.0.2
  flutter_native_splash: ^2.1.2+1
  google_nav_bar: ^5.0.5
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.20


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.4


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/videos/
    - assets/lottie/splash.json
    - assets/images/acelogo.png
    - assets/images/dish1.png
    - assets/images/dish2.png
    - assets/images/dish3.png
    - assets/images/dish4.png
    - assets/images/ingre1.png
    - assets/images/ingre2.png
    - assets/images/ingre3.png
    - assets/images/ingre4.png




